# Contenido definitivo y robusto para: .gitpod.yml

tasks:
  - name: Entorno Sui y Contrato
    init: |
      echo "--- [FASE 1/6] Iniciando Instalación de Rust y Cargo... ---"
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
      
      # CORRECCIÓN CLAVE: Hacemos 'export' del PATH para que esté disponible
      # para TODOS los comandos siguientes dentro de este script 'init'.
      export PATH="$HOME/.cargo/bin:$PATH"
      
      echo "\n--- [FASE 2/6] Verificando Cargo... ---"
      cargo --version
      
      # Usamos la v1.51.0 para que coincida con la versión del servidor de devnet y evitar warnings.
      echo "\n--- [FASE 3/6] Instalando Sui CLI v1.51.0 desde binarios... ---"
      wget -O sui.tgz https://github.com/MystenLabs/sui/releases/download/mainnet-v1.51.0/sui-mainnet-v1.51.0-ubuntu-x86_64.tar.gz
      tar -xzf sui.tgz
      # Usamos el comando 'mv' robusto que ya conocemos.
      mv sui-mainnet-v1.51.0-ubuntu-x86_64/sui ~/.cargo/bin/
      rm sui.tgz
      rm -rf sui-mainnet-v1.51.0-ubuntu-x86_64
      
      echo "\n--- [FASE 4/6] Verificando Sui CLI... ---"
      sui --version
      
      echo "\n--- [FASE 5/6] Configurando cliente de Sui para devnet... ---"
      # Ahora el comando 'sui' se encontrará sin problemas.
      sui client new-env --alias devnet --rpc https://fullnode.devnet.sui.io:443
      sui client switch --env devnet

      echo "\n--- [FASE 6/6] Instalando dependencias del cliente TypeScript... ---"
      cd app_client_logic
      npm install
      
      echo "\n\n--- ✅ Instalación de herramientas base completada. ---"
      
    command: |
      source "$HOME/.cargo/env"
      echo "✅ Entorno listo. Bienvenido de vuelta, colega."
      cd sui_contract

  - name: Cliente (TypeScript)
    command: |
      echo "✅ Terminal del Cliente lista."
      cd app_client_logic

  - name: General / Git
    command: |
      echo "✅ Terminal General lista para comandos de Git."

vscode:
  extensions:
    - rust-lang.rust-analyzer@prerelease
    - esbenp.prettier-vscode